### PR TITLE
Fix script tag replacer

### LINKED ISSUE #279: Change to use wp_enqueue has made gtag.js load synchronously
### Describe the bug:
The commit made in https://github.com/woocommerce/woocommerce-google-analytics-integration/commit/730495a09bbb22798f897a64907ceeccf278dcb5#diff-75fada6b677c39f17a7de173a315db4d8911e7469f5a70dce4822a6aaa849514 has switched to loading gtag using wp_queue_script. Unfortunately this has meant gtag lost its async tag and is loading render blocking. Scores on Core Web Vitals show. 

### Steps to reproduce:
1. Upgrade to a version of the plugin post this commit
2. View source
3. gtag script has no async tag

### Expected behavior:
Tag should load async to improve Woocommerce performance

### Actual behavior:
Change regressed performance due to synchronous JS

### Additional details:
image

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Closes #279 

### Checks:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Detailed test instructions:

1. Dont check out this PR and create this filter
```php
add_filter( 'script_loader_tag', array( $this, 'change_script_tags' ), 1, 3 );
function change_script_tags( $tag, $handle, $src ) {
		if ( in_array( $handle, self::ASYNC_SCRIPT_HANDLES, true ) ) {
			$tag = '<script type="text/javascript" src="' . $src . '" id="' . $handle . '-js"></script>';
		}
		return $tag;
	}
```
2. Go to the Shop and search for `google-tag-manager` script in the source
3. See "async" attribute not being added
4. Checkout this PR
5. Refresh
6.  See "async" attribute being added

### Changelog entry

> Fix - Add async attribute in `google-tag-manager` script.

### CODE REVIEW

**Review by eason9487 — DISMISSED** [review]
Thanks for the fix.

This is not a blocker, but it would be a bit better to avoid having two `async` attributes, even though it won't cause any real problems. (One of the `async` attributes seems to come from WC-Blocks)

image

**Comment by puntope** [comment]
Howdy @eason9487 thanks for that catch. Might you test again with this change https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/287/commits/f5712943354124b17204cf11f2b5e72bf3f9d1b6 ?

Thanks

File: includes/class-wc-google-analytics.php [hunk 1]
```diff
@@ -722,6 +722,13 @@ public function async_script_loader_tags( $tag, $handle, $src ) {
 			return $tag;
 		}
 
-		return str_replace( '<script src', '<script async src', $tag );
+		// Check if the script has the async attribute already. If so, don't add it again.
+		$has_async_tag = preg_match( '/^.*async.*$/', $tag );
```
Comment (eason9487) [inline includes/class-wc-google-analytics.php]: Two `async` attributes still occur as this regex pattern cannot match correctly. Maybe consider matching it with a pattern like `/\basync\b/`?

**Comment by puntope** [comment]
Thanks @eason9487, for me it seems like working in Firefox and Chrome... but I replaced it with your solution here https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/287/commits/e3dd72ce11a4a0bb3b7b04c011f3be2a4be5c7c8 

Can you check one more time?
Thanks

**Review by eason9487 — APPROVED** [review]
Thanks for the fix. LGTM.


> for me it seems like working in Firefox and Chrome... [...]

Not sure what makes them different. In my testing env, the `$tag` content includes two `script` tags at a time and is separated by a linebreak char as the following, so the previous regex pattern couldn't match.

```html
<script async src='https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX' id='google-tag-manager-js'></script>
<script id='google-tag-manager-js-after'>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', 'G-XXXXXXXXXX', { 'send_page_view': false });
</script>
```
