### PR TITLE
Fix usage of tracker_var() in load_analytics()

### LINKED ISSUE #185: Inconsistent usage of woocommerce_ga_tracker_variable
A filter named `woocommerce_ga_tracker_variable` exists which allows `gtag` and `ga` to be changed. Some calls to Google Analytics then use this, e.g:

```
' . self::tracker_var() . "( 'ec:addImpression', {
```

However, usage is inconsistent. There are many hardcoded gtag and ga calls through the codebase. If the filter is used, these calls can break.

I'd suggest removing the filter and using the correct methods throughout.

### PR DESCRIPTION
**Pull request by martynmjones**
### Changes proposed in this Pull Request:

In some places, the code in `WC_Google_Gtag_JS::load_analytics()` was directly printing `gtag()` when setting up the tracking instance. This PR adjusts the code so that `tracker_var()` is used in its place to ensure the filter `woocommerce_gtag_tracker_variable` is applied consistently.

Closes #185.

### Checks:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Screenshots:

Screenshot 2023-01-13 at 06 35 17

Screenshot 2023-01-13 at 06 38 50

### Detailed test instructions:
1. Checkout `fix/185-usage-of-tracker_var-in-setup` on a test site that has the extension active and set up
2. Use the `woocommerce_gtag_tracker_variable` filter to alter the default tracker var
_Example:_
```
add_filter(
	'woocommerce_gtag_tracker_variable',
	function( $tracker_var ) {
		return 'filteredGtag';
	}
);
```
3. View source of the frontend of your site and search for the inline script output by [load_analytics()](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/86193d93b4973c03269b7ae603e55264dca8887c/includes/class-wc-google-gtag-js.php#L258)
4. Confirm that all instances of `gtag()` have been replaced with the filtered tracker var

### CODE REVIEW

File: includes/class-wc-google-gtag-js.php [hunk 1]
```diff
@@ -476,3 +476,10 @@ public function event_tracking_code( $parameters, $selector ) {
 	}
 
 }
+
+add_filter(
+	'woocommerce_gtag_tracker_variable',
+	function( $tracker_var ) {
+		return 'filteredGtag';
+	}
+);
```
Comment (mikkamp) [inline includes/class-wc-google-gtag-js.php]: I assume this was just for testing and not intended to end up in the final PR.

**Review by mikkamp — APPROVED** [review]
Thanks, it looks good and is working as expected. I can't find any other instances where the helper function isn't used.

Since the usage is 4 times within the function I would have contemplated using a variable and then use it in the string as `{$tracker_var}`, that would prevent having to switch back and forth between single and double quotes.

I'll go ahead and approve it but it just needs the test filter snippet removed.

File: includes/class-wc-google-gtag-js.php (hunk 1 above)
Comment (martynmjones) [reply includes/class-wc-google-gtag-js.php]: 🤦 Thanks for picking up on that @mikkamp that was absolutely a mistake. I've removed the stray filter 👍
